version: "3.9"

services:
  database:
    image: postgres:16.4
    container_name: roadmap_ai__database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgres/data
    ports:
      - ${DB_FORWARD_PORT}:${DB_PORT}
    networks:
      - roadmap_ai
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: roadmap_ai__api
    depends_on:
      database:
        condition: service_healthy
    command: fastapi run roadmap_ai/main.py --port ${API_PORT}
    volumes:
      - .:/app
    ports:
      - ${API_FORWARD_PORT}:${API_PORT}
    stdin_open: true
    tty: true
    networks:
      - roadmap_ai

  pgadmin:
    image: dpage/pgadmin4
    container_name: roadmap_ai__pgadmin
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: Coffee897
    ports:
      - "8200:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - roadmap_ai
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - roadmap_ai

volumes:
  db_data:
  pgadmin_data:
  rabbitmq_data:

networks:
  roadmap_ai:
    driver: bridge
